# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.BigIntegerField(help_text='The ID that YouTube uses to uniquely identify the comment. comes from id', primary_key=True, serialize=False)),
                ('comment_author_display_name', models.TextField(help_text='can be fetched from snippet.authorDisplayName')),
                ('comment_text', models.TextField(help_text='the comment text')),
                ('like_count', models.BigIntegerField(help_text='comment like count')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_channel_id', models.TextField(help_text='user display name comes from comments: snippets.authorDisplayName', primary_key=True, serialize=False)),
                ('user_channel_title', models.TextField(help_text='comes from the channels api snippet.title')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('video_id', models.CharField(help_text='Youtube unique video id', max_length=500, primary_key=True, serialize=False)),
                ('video_name', models.TextField(help_text='video name caption')),
                ('video_view_count', models.BigIntegerField(help_text='number of video view count')),
                ('video_comment_count', models.BigIntegerField(help_text='number of video comments')),
                ('video_embedable', models.BooleanField(help_text='this value indicates whether the video can be embedded on another website (ours :)')),
                ('video_url', models.TextField(help_text="embed url of the video it's the embedHtml field in player key, is the video isn't embeddable the video url is a regular video.")),
                ('video_channel_id', models.ForeignKey(help_text='comes from the snippets.ChannelId', on_delete=django.db.models.deletion.CASCADE, to='searcher.Users')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_channel_id',
            field=models.ForeignKey(help_text='Comes from snippet.authorChannelId.value', on_delete=django.db.models.deletion.CASCADE, to='searcher.Users'),
        ),
        migrations.AddField(
            model_name='comments',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searcher.Videos'),
        ),
    ]
